import streamlit as st
import pandas as pd

# --- CSS Personalizado para Layout e Estilo ---
st.markdown("""
<style>
    /* Ajuste do layout principal */
    .block-container {
        padding-top: 2rem;
        padding-bottom: 0rem;
        padding-left: 1rem;
        padding-right: 1rem;
    }

    /* Estilo do título */
    .st-emotion-cache-1jm98c7 {
        text-align: center;
        color: #2C005A;
        font-family: 'Arial', sans-serif;
    }

    /* Centraliza a imagem da logo */
    .st-emotion-cache-nahz7x {
        display: flex;
        justify-content: center;
        margin-bottom: 20px;
    }

    /* Estilo para a sidebar */
    .st-emotion-cache-1c19ghu {
        background-color: #F0F8FF;
        color: #2C005A;
    }

    /* Botões arredondados com sombra */
    .st-emotion-cache-vk3377 {
        border-radius: 8px;
        box-shadow: 2px 2px 5px rgba(0,0,0,0.1);
    }

    /* Estilo para o file uploader */
    .st-emotion-cache-b9f4a8 p {
        font-size: 1.1em;
        font-weight: bold;
        color: #2C005A;
    }
</style>
""", unsafe_allow_html=True)

# --- Logo e Título ---
st.image("logo_dati.png", width=200)  # Certifique-se que a logo está na mesma pasta que app.py
st.title("Resumo Financeiro da AWS")

# --- Upload do Arquivo ---
uploaded_file = st.file_uploader("Envie seu arquivo CSV de calculadora AWS aqui", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    st.success("Arquivo carregado com sucesso!")

    # --- Resumo Inicial ---
    st.subheader("Visão Geral do Resumo")
    st.write(df.head())  # Exibe as primeiras linhas do CSV

    # --- Container para resumo e métricas ---
    with st.container(border=True):
        st.write("Aqui viriam os gráficos ou tabelas de resumo financeiro.")
        st.metric(label="Custo Total Estimado", value="R$ 1.234,56", delta="R$ 50,00 (Semana Passada)")

    # --- Sidebar ---
    with st.sidebar:
        st.header("Opções")
        selected_option = st.radio("Escolha o período:", ("Mensal", "Semanal", "Anual"))
        st.button("Gerar Relatório Detalhado")
